apiVersion: apps/v1
kind: Deployment
metadata:
  name: web-app
spec:
  selector:
    matchLabels:
      app: web-app
  replicas: 3 # tells deployment to run 3 pods matching the template
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 0   # 🔥 guarantees zero downtime
      maxSurge: 1     # 🔥 allows one extra pod to be created during the update, ensuring that there is always at least one pod available to serve traffic.
  template:
    metadata:
      labels:
        app: web-app
    spec:
      containers:
      - name: web-app
        image: vaninoel/myweb:1.0
        ports:
        - containerPort: 5000
       
        readinessProbe:
          httpGet:
            path: /health
            port: 5000
          initialDelaySeconds: 15
          periodSeconds: 10

        livenessProbe:
          httpGet:
            path: /health
            port: 5000
          initialDelaySeconds: 15
          periodSeconds: 10
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
          requests:
            memory: "64Mi"
            cpu: "250m"
