pipeline {
    agent any

    environment {
        IMAGE_NAME = 'vaninoel/jenkins-python-app'
        IMAGE_TAG = "${BUILD_NUMBER}"
    }

    stages {

        stage('Checkout Code') {
            steps {
                echo 'Cloning repository...'
                git branch: 'main', url: 'https://github.com/bcho77/Devops_projects.git'
            }
        }

        stage('Install dependencies') {
            steps {
                echo 'Installing dependencies...'
                dir('CI/CD_Complet_Projects/simple_Web_app') {
                    sh '''
                        python3 -m venv venv
                        . venv/bin/activate
                        pip install --upgrade pip
                        pip install -r requirements.txt
                    '''
                }
            }
        }

        stage('Run tests') {
            steps {
                echo 'Running tests...'
                dir('CI/CD_Complet_Projects/simple_Web_app') {
                    sh '''
                        . venv/bin/activate
                        pytest test_app.py
                    '''
                }
            }
        }

        stage('Build Docker Image') {
            steps {
                echo 'Building Docker image...'
                dir('CI/CD_Complet_Projects/simple_Web_app') {
                    sh '''
                        docker build -t $IMAGE_NAME:$IMAGE_TAG .
                        docker tag $IMAGE_NAME:$IMAGE_TAG $IMAGE_NAME:latest
                    '''
                }
            }
        }

        stage('Login to Docker Hub') {
            steps {
                withCredentials([usernamePassword(
                    credentialsId: 'docker-hub-credentials',
                    usernameVariable: 'DOCKER_USERNAME',
                    passwordVariable: 'DOCKER_PASSWORD'
                )]) {
                    sh '''
                        echo $DOCKER_PASSWORD | docker login -u $DOCKER_USERNAME --password-stdin
                    '''
                }
            }
        }

        stage('Push Docker Image') {
            steps {
                sh '''
                    docker push $IMAGE_NAME:$IMAGE_TAG
                    docker push $IMAGE_NAME:latest
                '''
            }
        }

        stage('Deploy to minikube with helm') {
            steps {
                echo 'Deploying to Kubernetes with Helm...'
                dir('CI/CD_Complet_Projects/simple_Web_app') {
                sh '''
                    pwd
                    ls -la
                    helm upgrade --install mypyweb ./mypyweb \
                    --set image.repository=$IMAGE_NAME \
                    --set image.tag=$IMAGE_TAG \
                    --namespace default
                '''
                }
            }
        }

        

    }
}




