pipeline {
    agent any

    environment {
        // Define any environment variables here
    IMAGE_NAME = 'vaninoel/jenkins-python-app:latest'
    IMAGE_TAG = '$BUILD_NUMBER'

    }


    stages {
        stage('Checkout') {
            steps {
                echo 'Checking out code...'
                // Add your checkout commands here
            git branch: 'main', url: ''
            }
        }
        stage('Build') {
            steps {
                echo 'Building...'
                // Add your build commands here
            }
        }
        stage('Test') {
            steps {
                echo 'Testing...'
                // Add your test commands here
            }
        }
        stage('Deploy') {
            steps {
                echo 'Deploying...'
                // Add your deploy commands here
            }
        }
    }
}